name: Checkout Repository

on:
  push:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    containers: almalinux 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
